### ISSUE TITLE
can be confusing knowing where to look to see depenencies

### ISSUE THREAD

**Issue by xdaDaveShaw** [DevSnicket/eunice#156]
Whilst drilling down into some interdependencies, I was confused when I got to this view:

![image](https://user-images.githubusercontent.com/2511715/90406723-7c698980-e09d-11ea-9f07-a5c1836b49c7.png)

I had being following the Red `>` to drill down, the view before was this:

![image](https://user-images.githubusercontent.com/2511715/90406903-ba66ad80-e09d-11ea-92c5-56ac4bf7d92a.png)

However, when I got to the view in the first image, I misunderstood the "summary" at the bottom to mean CollectionExtensions had interdependencies instead of the Application.

Some time was lost trying to figure out the reason for CollectionExtension having interdependencies, when in fact I should have opened Application to see the problem.

**Comment by grahamdyson** [comment]
I think I understand where the confusing part is.

Do you think the parent's name (top) and summary (bottom) will appear more clearly related (and separate from the child items) by giving them a background that joins them together with the border...

![issue 156](https://user-images.githubusercontent.com/8238768/90411512-cf463f80-e0a3-11ea-8700-dd3228702186.png)

**Comment by xdaDaveShaw** [comment]
Yeah, that looks clearer.

As I now know what I did wrong, in hindsight it is hard to tell if I wouldn't do it again, but this definitely separates things better.

**Comment by grahamdyson** [comment]
released in [JavaScript 7.14.0](https://devsnicket.com/eunice/javascript/releases#7.14.0)

**Comment by grahamdyson** [comment]
released in [C# 1.20.0](https://devsnicket.com/eunice/csharp/releases#1.20.0)

**Comment by xdaDaveShaw** [comment]
Ran a few more recent tests and noticed my eyes heading to the bottom red chevron, but the border made me look back up for the actual violation.

Definitely working for me :)

**Comment by grahamdyson** [comment]
> Ran a few more recent tests and noticed my eyes heading to the bottom red chevron, but the border made me look back up for the actual violation.
> 
> Definitely working for me :)

good to hear, thanks for raising the issue
